---
- hosts: localhost
  become: yes
  tasks:
  - name: install packages
    yum: name={{ item }} state=latest 
    with_items:
      - bind
      - bind-utils
      - ntp
      - libsemanage-python

  - name: copy transferkey to all servers and the client
    copy: src=/vagrant/provisioning/named.zonetransfer.key dest=/etc/named.zonetransfer.key owner=root group=named mode=0644

  - name: copy resolv.conf to the client
    copy: src=/vagrant/provisioning/client-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644

  - name: copy rndc conf file
    copy: src=/vagrant/provisioning/rndc.conf dest=/home/vagrant/rndc.conf owner=vagrant group=vagrant mode=0644

  - name: copy motd to the client
    copy: src=/vagrant/provisioning/client-motd dest=/etc/motd owner=root group=root mode=0644
    