---
- hosts: localhost
  become: yes
  tasks:
  - name: install packages
    yum: name={{ item }} state=latest 
    with_items:
      - bind
      - bind-utils
      - ntp
      - libsemanage-python

  - name: copy named.conf
    copy: src=/vagrant/provisioning/master-named.conf dest=/etc/named.conf owner=root group=named mode=0640
  
  - name: copy zones
    copy: src={{ item }} dest=/etc/named/ owner=root group=named mode=0660
    with_fileglob:
      - /vagrant/provisioning/named.d*
  
  - name: copy resolv.conf to the servers
    copy: src=/vagrant/provisioning/servers-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644
  
  - name: set /etc/named permissions
    file: path=/etc/named owner=root group=named mode=0670

  - name: selinux /etc/named/
    sefcontext:
      target: '/etc/named(/.*)?'
      setype: named_zone_t
      state: present
      reload: yes
    register: selinux
    
  - name: apply  file context 
    shell: |
      restorecon -Rv /etc/named
    when: selinux.changed
    
  - name: ensure named is running and enabled
    service: name=named state=restarted enabled=yes